services:
  - type: web
    name: swapi-wrapper-api
    env: docker
    plan: free
    region: frankfurt 
    branch: master     
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "dotnet SwapiWrapperApi.dll"
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        sync: false
      - key: JWT_ISSUER
        sync: false
      - key: JWT_AUDIENCE
        sync: false
